name: Sync to Hugging Face hub
on:
  push:
    branches: [main]

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      
      - name: Force Push Fresh Code
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # 1. Git Setup
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          
          # 2. Purani History delete karo
          rm -rf .git
          
          # 3. Naya Git Init aur Branch rename (YE LINE MISSING THI ðŸ‘‡)
          git init
          git branch -m main
          
          git lfs install
          
          # 4. Images track karo
          git lfs track "*.png"
          git lfs track "*.jpg"
          git lfs track "*.jpeg"
          git lfs track "*.ico"
          
          # 5. Add aur Commit
          git add .
          git commit -m "Fresh Deploy Force Fix"
          
          # 6. Push karo (Ab ye chalega)
          git push --force https://Shantanupathak94:$HF_TOKEN@huggingface.co/spaces/Shantanupathak94/Shanvika-Ai main
