name: Sync to Hugging Face hub
on:
  push:
    branches: [main]

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      
      - name: Force Push Fresh Code
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # 1. Git Setup
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          
          # 2. Purani History (Jisme error hai) ko uda do
          rm -rf .git
          
          # 3. Naya Git Init karo (Fresh Start)
          git init
          git lfs install
          
          # 4. Images ko sahi tarike se track karo
          git lfs track "*.png"
          git lfs track "*.jpg"
          git lfs track "*.jpeg"
          git lfs track "*.ico"
          
          # 5. Files Add aur Commit karo
          git add .
          git commit -m "Fresh Deploy Force Fix"
          
          # 6. Zabardasti (Force) Push karo
          git push --force https://Shantanupathak94:$HF_TOKEN@huggingface.co/spaces/Shantanupathak94/Shanvika-Ai main
